---
- name: add apt repo
  apt_repository: repo='{{ item.repo }}' state=present
  with_items: "{{ apt_repository_repositories }}"
  register: result

- name: add apt key
  apt_key: "url={{ item.key }} state=present"
  with_items: "{{ apt_repository_repositories }}"
  when: item.key is defined

- name: update apt cache
  apt: update_cache=yes
  when: result.stdout == "changed"
